import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header>
					<nav>
						<ul className='flex gap-4'>
							<li>
								<Link href='/'>Characters</Link>
							</li>
							<li>
								<Link href='/locations'>Locations</Link>
							</li>
							<li>
								<Link href='/episodes'>Episodes</Link>
							</li>
							<li>
								<Link href='/login'>Вход</Link>
							</li>
						</ul>
					</nav>
				</header>
				<main>{children}</main>
				<footer>Это футер</footer>
			</body>
		</html>
	)
}
